const words = [
    { word: "agitate", zh: "激动 鼓动", soundmark: "[ˈædʒɪˌteɪt]", eg: "The speech agitated the crowd.", "egzh": "演讲激动了人群。", "feat": "动词" },
    { word: "anniversary", zh: "周年纪念", soundmark: "[ˌænɪˈvɜrsəri]", eg: "They celebrated their 25th wedding anniversary.", "egzh": "他们庆祝了他们的25周年婚礼纪念日。", "feat": "名词" },
    { word: "auditorium", zh: "礼堂", soundmark: "[ˌɔːdɪˈtɔːriəm]", eg: "The auditorium was filled with students for the lecture.", "egzh": "礼堂里坐满了听讲座的学生。", "feat": "名词" },
    { word: "august", zh: "威严的", soundmark: "[ɔːˈɡʌst]", eg: "His august presence commanded respect.", "egzh": "他威严的出席令人尊敬。", "feat": "形容词" },
    { word: "auction", zh: "拍卖", soundmark: "[ˈɔːkʃən]", eg: "The artwork was sold at an auction for a high price.", "egzh": "这幅艺术品以高价在拍卖会上卖出。", "feat": "名词" },
    { word: "capable", zh: "有能力的", soundmark: "[ˈkeɪpəbl]", eg: "She is a capable leader.", "egzh": "她是一个有能力的领导。", "feat": "形容词" },
    { word: "capability", zh: "能力", soundmark: "[ˌkeɪpəˈbɪləti]", eg: "The team demonstrated its capability to solve complex problems.", "egzh": "团队展示了解决复杂问题的能力。", "feat": "名词" },
    { word: "capacity", zh: "容量", soundmark: "[kəˈpæsəti]", eg: "The tank has a capacity of 100 liters.", "egzh": "这个储罐的容量是100升。", "feat": "名词" },
    { word: "captive", zh: "被俘虏的", soundmark: "[ˈkæptɪv]", eg: "The captive soldiers were treated well by their captors.", "egzh": "被俘虏的士兵受到了俘虏者的善待。", "feat": "形容词" },
    { word: "capture", zh: "捕获", soundmark: "[ˈkæptʃər]", eg: "They managed to capture the rare bird on camera.", "egzh": "他们设法在照相机上捕获到了这只稀有鸟。", "feat": "动词" },
    { word: "augment", zh: "增加", soundmark: "[ɔːɡˈmɛnt]", eg: "They decided to augment their team with new members.", "egzh": "他们决定增加新成员来壮大他们的团队。", "feat": "动词" },
    { word: "coincide", zh: "同时发生", soundmark: "[ˌkoʊˈɪn.saɪd]", eg: "Our schedules coincide, so we can meet.", "egzh": "我们的时间安排相符，所以我们可以见面。", "feat": "动词" }, { word: "authority", zh: "权威", soundmark: "[əˈθɔrəti]", eg: "She is an authority on the subject of climate change.", "egzh": "她是气候变化领域的权威。", "feat": "名词" },
    { word: "authorize", zh: "授权", soundmark: "[ˈɔːθəraɪz]", eg: "The manager will authorize the payment.", "egzh": "经理将授权付款。", "feat": "动词" },
    { word: "decadent", zh: "颓废的", soundmark: "[ˈdɛkədənt]", eg: "The society was known for its decadent lifestyle.", "egzh": "这个社会以其颓废的生活方式而闻名。", "feat": "形容词" },
    { word: "casual", zh: "随意的", soundmark: "[ˈkæʒuəl]", eg: "He wore a casual T-shirt and jeans.", "egzh": "他穿着一件随意的T恤和牛仔裤。", "feat": "形容词" },
    { word: "coincidence", zh: "巧合", soundmark: "[koʊˈɪn.sɪ.dəns]", eg: "It's just a coincidence that we both chose the same restaurant.", "egzh": "我们两个选择了同一家餐厅，这只是巧合。", "feat": "名词" },
    { word: "coincident", zh: "巧合的", soundmark: "[koʊˈɪn.sɪ.dənt]", eg: "Their arrival at the same time was purely coincident.", "egzh": "他们同时到达纯粹是巧合。", "feat": "形容词" }, { word: "incident", zh: "事件", soundmark: "[ˈɪn.sɪ.dənt]", eg: "The incident was reported to the police.", "egzh": "事件已经报告给了警察。", "feat": "名词" },
    { word: "incidence", zh: "发生率", soundmark: "[ˈɪn.sɪ.dəns]", eg: "The incidence of the disease has increased.", "egzh": "这种疾病的发生率增加了。", "feat": "名词" },
    { word: "receive", zh: "接收", soundmark: "[rɪˈsiːv]", eg: "I will receive the package tomorrow.", egzh: "明天我将接收包裹。", feat: "verb" },
    { word: "receiver", zh: "接收器", soundmark: "[rɪˈsiːvər]", eg: "He bought a new receiver for his stereo system.", egzh: "他为他的音响系统买了一个新的接收器。", feat: "noun" },
    { word: "principal", zh: "主要的|校长", soundmark: "[ˈprɪnsəpl]", eg: "The principal reason for his success is hard work.", egzh: "他成功的主要原因是努力工作。", feat: "adjective" },
    { word: "participate", zh: "参加", soundmark: "[pɑrˈtɪsɪˌpeɪt]", eg: "Will you participate in the charity event?", egzh: "你会参加慈善活动吗？", feat: "verb" },
    { word: "career", zh: "职业生涯|经历事业|疾驰飞奔", soundmark: "[kəˈrɪr]", eg: "She has had a successful career in finance.", egzh: "她在金融领域有着成功的职业生涯。", feat: "noun" },
    { word: "carriage", zh: "马车|火车的客车厢|四轮马车", soundmark: "[ˈkærɪdʒ]", eg: "The wedding carriage was beautifully decorated.", egzh: "婚礼马车装饰得很美。", feat: "noun" },
    { word: "charge", zh: "费用|收费|职责|赋予责任|控告", soundmark: "[ʧɑrdʒ]", eg: "What is the charge for using the gym?", egzh: "使用健身房要多少费用？", feat: "noun" },
    { word: "deceive", zh: "欺骗", soundmark: "[dɪˈsiːv]", eg: "She tried to deceive him, but he saw through her lies.", egzh: "她试图欺骗他，但他看穿了她的谎言。", feat: "verb" },
    { word: "deceit", zh: "欺骗", soundmark: "[dɪˈsiːt]", eg: "His deceit was exposed.", egzh: "他的欺骗被揭露了。", feat: "noun" },
    { word: "deception", zh: "欺骗", soundmark: "[dɪˈsɛpʃən]", eg: "She saw through his deception.", egzh: "她看穿了他的欺骗。", feat: "noun" },
    { word: "reception", zh: "接待", soundmark: "[rɪˈsɛpʃən]", eg: "The hotel has a beautiful reception area.", egzh: "酒店有一个漂亮的接待区。", feat: "noun" },
    { word: "receptive", zh: "善于接受的", soundmark: "[rɪˈsɛptɪv]", eg: "She is very receptive to new ideas.", egzh: "她对新思想非常接受。", feat: "adjective" },
    { word: "recipe", zh: "食谱", soundmark: "[ˈrɛsəpi]", eg: "I found a great recipe for spaghetti online.", egzh: "我在网上找到了一份很棒的意大利面食谱。", feat: "noun" },
    { word: "conceive", zh: "构想", soundmark: "[kənˈsiːv]", eg: "She could not conceive of a world without music.", egzh: "她无法构想没有音乐的世界。", feat: "verb" },
    { word: "conceivable", zh: "可想象的", soundmark: "[kənˈsiːvəbl]", eg: "It is conceivable that he will arrive late.", egzh: "他可能会迟到。", feat: "adjective" },
    { word: "conception", zh: "概念", soundmark: "[kənˈsɛpʃən]", eg: "The artist had a unique conception of beauty.", egzh: "这位艺术家对美的概念独具特色。", feat: "noun" },
    { word: "conceptive", zh: "概念的|有构想力的", soundmark: "[kənˈsɛptɪv]", eg: "The book explores the conceptive aspects of art.", egzh: "这本书探讨了艺术的概念方面。", feat: "adjective" },
    { word: "conceptual", zh: "概念的", soundmark: "[kənˈsɛptʃuəl]", eg: "The project has both practical and conceptual elements.", egzh: "这个项目既有实际的又有概念的元素。", feat: "adjective" },
    { word: "campaign", zh: " 战役|运动", soundmark: "[kæmˈpeɪn]", eg: "The political campaign was well-organized.", egzh: "这次政治运动组织有序。", feat: "noun" },
    { word: "champion", zh: "冠军", soundmark: "[ˈʧæmpiən]", eg: "She is the reigning champion of the competition.", egzh: "她是比赛的卫冕冠军。", feat: "noun" },
    { word: "champagne", zh: "香槟", soundmark: "[ʃæmˈpeɪn]", eg: "Let's celebrate with a bottle of champagne.", egzh: "让我们用一瓶香槟庆祝。", feat: "noun" },
    { word: "candle", zh: "蜡烛", soundmark: "[ˈkændl]", eg: "They lit a candle to create a romantic atmosphere.", egzh: "他们点燃了蜡烛营造浪漫氛围。", feat: "noun" },
    { word: "candidate", zh: "候选人", soundmark: "[ˈkændɪˌdeɪt]", eg: "The candidate promised to improve education.", egzh: "候选人承诺改善教育。", feat: "noun" },
    { word: "carton", zh: "纸盒", soundmark: "[ˈkɑrtən]", eg: "The milk comes in a carton.", egzh: "牛奶装在纸盒里。", feat: "noun" },
    { word: "process", zh: "过程", soundmark: "[ˈprɑsɛs]", eg: "The manufacturing process is highly efficient.", egzh: "制造过程非常高效。", feat: "noun" },
    { word: "access", zh: "访问|通道，通路|机会，权利 ", soundmark: "[ˈæksɛs]", eg: "Employees have access to the company's intranet.", egzh: "员工可以访问公司的内部网络。", feat: "noun" },
    { word: "successive", zh: "连续的", soundmark: "[səkˈsɛsɪv]", eg: "The company has had three successive quarters of growth.", egzh: "该公司连续三个季度实现增长。", feat: "adjective" },
    { word: "succession", zh: "连续|交替；继承", soundmark: "[səkˈsɛʃən]", eg: "The succession of events led to the final outcome.", egzh: "一系列事件导致了最终结果。", feat: "noun" },
    { word: "percent", zh: "百分之", soundmark: "[pərˈsɛnt]", eg: "Twenty percent of the population lives in urban areas.", egzh: "百分之二十的人口居住在城市地区。", feat: "noun" },
    { word: "percentage", zh: "百分比", soundmark: "[pərˈsɛntɪdʒ]", eg: "What is the percentage of students who passed the exam?", egzh: "通过考试的学生百分比是多少？", feat: "noun" },
    { word: "secret", zh: "秘密", soundmark: "[ˈsiːkrət]", eg: "Can you keep a secret?", egzh: "你能保守秘密吗？", feat: "noun" },
    { word: "secretary", zh: "秘书", soundmark: "[ˈsɛkrəˌtɛri]", eg: "The secretary scheduled the meeting.", egzh: "秘书安排了会议。", feat: "noun" },
    { word: "central", zh: "中心的", soundmark: "[ˈsɛntrəl]", eg: "The central location made it easy to access the city's attractions.", egzh: "中心位置使得前往城市景点很方便。", feat: "adjective" },
    { word: "cent", zh: "分", soundmark: "[sɛnt]", eg: "A dollar is made up of 100 cents.", egzh: "一美元由100分组成。", feat: "noun" },
    { word: "century", zh: "世纪", soundmark: "[ˈsɛnʧəri]", eg: "The 20th century was a period of significant change.", egzh: "20世纪是一个重大变革的时期。", feat: "noun" },
    { word: "agenda", zh: "议程", soundmark: "[əˈdʒɛndə]", eg: "The meeting agenda includes various topics to discuss.", "egzh": "会议议程包括讨论各种话题。", "feat": "名词" },
    { word: "concentrate", zh: "集中", soundmark: "[ˈkɑnsəˌtreɪt]", eg: "She needed to concentrate on her studies.", egzh: "她需要集中精力学习。", feat: "verb" },
    { word: "concentration", zh: "集中", soundmark: "[ˌkɑnsənˈtreɪʃən]", eg: "The concentration of students in the library was impressive.", egzh: "图书馆里学生的集中程度令人印象深刻。", feat: "noun" },
    { word: "eccentric", zh: "古怪的", soundmark: "[ɪkˈsɛntrɪk]", eg: "His eccentric behavior often surprised his friends.", egzh: "他古怪的行为经常让朋友们感到惊讶。", feat: "adjective" },
    { word: "certain", zh: "确定的", soundmark: "[ˈsɜrtn]", eg: "I am certain that he will come to the party.", egzh: "我确定他会来参加派对。", feat: "adjective" },
    { word: "certainly", zh: "当然", soundmark: "[ˈsɜrtnli]", eg: "Certainly, you can borrow my book.", egzh: "当然，你可以借我的书。", feat: "adverb" },
    { word: "ascertain", zh: "确定", soundmark: "[ˌæsərˈteɪn]", eg: "He needed to ascertain the truth of the matter.", egzh: "他需要确定事情的真相。", feat: "verb" },
    { word: "certify", zh: "证明", soundmark: "[ˈsɜrtəˌfaɪ]", eg: "The document is certified by the authorities.", egzh: "这份文件由当局证明。", feat: "verb" },
    { word: "decide", zh: "决定", soundmark: "[dɪˈsaɪd]", eg: "It's time to decide on a plan of action.", egzh: "是时候决定行动计划了。", feat: "verb" },
    { word: "decided", zh: "决定的", soundmark: "[dɪˈsaɪdɪd]", eg: "After much discussion, they reached a decided course of action.", egzh: "经过长时间的讨论，他们达成了明确的行动方案。", feat: "adjective" },
    { word: "decision", zh: "决定", soundmark: "[dɪˈsɪʒən]", eg: "The decision was made after careful consideration.", egzh: "这个决定经过仔细考虑后做出的。", feat: "noun" },
    { word: "concise", zh: "简明的", soundmark: "[kənˈsaɪs]", eg: "The report provides a concise summary of the findings.", egzh: "这份报告简明扼要地总结了研究结果。", feat: "adjective" },
    { word: "precise", zh: "精确的", soundmark: "[prɪˈsaɪs]", eg: "The measurements need to be precise for accurate results.", egzh: "测量必须精确以获得准确的结果。", feat: "adjective" },
    { word: "precision", zh: "精确", soundmark: "[prɪˈsɪʒən]", eg: "The precision of the equipment is impressive.", egzh: "这台设备的精确度令人印象深刻。", feat: "noun" },
    { word: "suicide", zh: "自杀", soundmark: "[ˈsuɪˌsaɪd]", eg: "Suicide is a serious public health concern.", egzh: "自杀是一个严重的公共卫生问题。", feat: "noun" },
    { word: "occasional", zh: "偶尔的", soundmark: "[əˈkeɪʒənl]", eg: "I take occasional breaks during work.", "egzh": "我在工作中偶尔休息。", "feat": "形容词" },
    { word: "accident", zh: "事故", soundmark: "[ˈæk.sɪ.dənt]", eg: "The car accident caused injuries.", "egzh": "车祸导致了伤害。", "feat": "名词" },
    { word: "accidental", zh: "偶然的", soundmark: "[ˌæk.sɪˈden.təl]", eg: "His discovery was accidental, not intentional.", "egzh": "他的发现是偶然的，不是故意的。", "feat": "形容词" },
    { word: "incidental", zh: "附带的", soundmark: "[ˌɪn.sɪˈdɛn.təl]", eg: "The damage was incidental to the main issue.", "egzh": "这些损害与主要问题无关。", "feat": "形容词" },
    { word: "incidentally", zh: "顺便提一下", soundmark: "[ˌɪn.sɪˈdɛntəli]", eg: "Incidentally, I met your sister yesterday.", "egzh": "顺便说一下，我昨天见到了你的姐姐。", "feat": "副词" },
    { word: "susceptible", zh: "易受影响的 易受感动的，感情丰富的", soundmark: "[sԥˈseptԥbl]", eg: "He is susceptible to suggestion. | A susceptible girl falls in love soon.", "egzh": "他是没有主见的 | 多情少女易坠情网", "feat": "形容词" },
    { word: "receipt", zh: "收据", soundmark: "[rɪˈsiːt]", eg: "Make sure to keep the receipt as proof of purchase.", egzh: "务必保留收据作为购买凭证。", feat: "noun" },
    { word: "perception", zh: "感知", soundmark: "[pərˈsiːpʃən]", eg: "Our perception of reality can be subjective.", egzh: "我们对现实的感知可能是主观的。", feat: "noun" },
    { word: "perceive", zh: "察觉", soundmark: "[pərˈsiːv]", eg: "He could perceive a change in her attitude.", egzh: "他察觉到了她态度的变化。", feat: "verb" },
    { word: "anticipate", zh: "预期|先于……做", soundmark: "[ænˈtɪsɪˌpeɪt]", eg: "I anticipate a great time at the party.", egzh: "我期待在派对上度过美好时光。", feat: "verb" },
    { word: "precede", zh: "在...之前", soundmark: "[prɪˈsiːd]", eg: "The introduction will precede the main presentation.", egzh: "引言将在主要演讲之前进行。", feat: "verb" },
    { word: "precedent", zh: "先例", soundmark: "[ˈprɛsɪdənt]", eg: "The court's decision set a precedent for future cases.", egzh: "法院的决定为未来的案件设立了先例。", feat: "noun" },
    { word: "preceding", zh: "在前的", soundmark: "[prɪˈsiːdɪŋ]", eg: "The preceding chapter provides important context.", egzh: "前一章提供了重要的背景。", feat: "adjective" },
    { word: "concede", zh: "承认|让步", soundmark: "[kənˈsiːd]", eg: "He had to concede that he was wrong.", egzh: "他不得不承认自己错了。", feat: "verb" },
    { word: "concession", zh: "让步", soundmark: "[kənˈsɛʃən]", eg: "The government made a concession to the protesters.", egzh: "政府对抗议者做出了让步。", feat: "noun" },
    { word: "concessive", zh: "让步的", soundmark: "[kənˈsɛsɪv]", eg: "She adopted a concessive tone in the negotiations.", egzh: "她在谈判中采取了让步的语气。", feat: "adjective" },
    { word: "casualty", zh: "伤亡", soundmark: "[ˈkæʒuəlti]", eg: "The war resulted in many casualties.", "egzh": "战争造成了许多伤亡。", "feat": "名词" },
    { word: "recede", zh: "后退", soundmark: "[rɪˈsiːd]", eg: "The floodwaters began to recede.", egzh: "洪水开始退去。", feat: "verb" },
    { word: "recession", zh: "经济衰退", soundmark: "[rɪˈsɛʃən]", eg: "The country faced a severe recession in the 2008 financial crisis.", egzh: "2008年的金融危机中，该国面临了严重的经济衰退。", feat: "noun" },
    { word: "exceed", zh: "超过", soundmark: "[ɪkˈsiːd]", eg: "The company's profits exceed expectations.", egzh: "公司的利润超出了预期。", feat: "verb" },
    { word: "excess", zh: "过多|超过", soundmark: "[ɪkˈsɛs]", eg: "Excess sugar consumption can lead to health problems.", egzh: "过多的糖摄入会导致健康问题。", feat: "noun" },
    { word: "excessive", zh: "过度的", soundmark: "[ɪkˈsɛsɪv]", eg: "His excessive spending caused financial troubles.", egzh: "他过度消费导致了财务问题。", feat: "adjective" },
    { word: "proceed", zh: "继续|行进；前往", soundmark: "[prəˈsiːd]", eg: "Please proceed with your presentation.", egzh: "请继续进行你的演示。", feat: "verb" },
    { word: "procession", zh: "队伍", soundmark: "[prəˈsɛʃən]", eg: "The wedding procession moved slowly down the aisle.", egzh: "婚礼队伍缓慢地沿着通道前进。", feat: "noun" },
    { word: "procedure", zh: "程序", soundmark: "[prəˈsiːdʒər]", eg: "Follow the correct procedure to complete the task.", egzh: "按照正确的程序完成任务。", feat: "noun" },
    { word: "ancestor", zh: "祖先,祖宗", soundmark: "[ˈænsɛstər]", eg: "Exploring one's ancestry can be a fascinating journey.", egzh: "探索自己的祖先可以是一段迷人的旅程。", feat: "noun" },
    { word: "predecessor", zh: "前任", soundmark: "[ˈprɛdəˌsɛsər]", eg: "The new CEO replaced her predecessor.", egzh: "新任CEO取代了她的前任。", feat: "noun" },
    { word: "circle", zh: "圆圈", soundmark: "ˈsɜːrkl", eg: "The children drew a circle on the paper.", "egzh": "孩子们在纸上画了一个圆圈。", "feat": "名词" },
    { word: "circuit", zh: "电路", soundmark: "ˈsɜːrkət", eg: "The electrician fixed the circuit in the house.", "egzh": "电工修理了房子里的电路。", "feat": "名词" },
    { word: "circular", zh: "圆形的", soundmark: "ˈsɜːrkjələr", eg: "The table had a circular top.", "egzh": "桌子的顶部是圆形的。", "feat": "形容词" },
    { word: "circulate", zh: "循环", soundmark: "ˈsɜːrkjəleɪt", eg: "Blood circulates in the human body.", "egzh": "血液在人体内循环。", "feat": "动词" },
    { word: "circulation", zh: "循环|血液循环", soundmark: "ˌsɜːrkjəˈleɪʃən", eg: "The circulation of the magazine is increasing.", "egzh": "这本杂志的发行量正在增加。", "feat": "名词" },
    { word: "circus", zh: "马戏团", soundmark: "ˈsɜːrkəs", eg: "We watched a great performance at the circus.", "egzh": "我们在马戏团观看了一场精彩的表演。", "feat": "名词" },
    { word: "circumstance", zh: "情况", soundmark: "ˈsɜːrkəmstæns", eg: "She is in a difficult circumstance.", "egzh": "她处于困境之中。", "feat": "名词" },
    { word: "circumference", zh: "周长", soundmark: "sərˈkəmfərəns", eg: "To find the circumference of a circle, you need to know its radius.", "egzh": "要找到圆的周长，你需要知道它的半径。", "feat": "名词" },
    { word: "claim", zh: "声称|宣称", soundmark: "kleɪm", eg: "He will claim the prize if he wins.", "egzh": "如果他赢了，他将声称奖品。", "feat": "动词" },
    { word: "exclaim", zh: "呼喊|惊叫|呼喊", soundmark: "ɪkˈskleɪm", eg: "She exclaimed with joy when she saw the surprise.", "egzh": "当她看到惊喜时，她高兴地呼喊了出来。", "feat": "动词" },
    { word: "exclamation", zh: "感叹", soundmark: "ˌɛkskləˈmeɪʃən", eg: "His exclamation of surprise filled the room.", "egzh": "他惊讶的感叹充满了房间。", "feat": "名词" },
    { word: "acclaim", zh: "赞誉", soundmark: "əˈkleɪm", eg: "The performance received critical acclaim.", "egzh": "这次表演受到了批评家的赞誉。", "feat": "名词" },
    { word: "proclaim", zh: "宣布|声明", soundmark: "proʊˈkleɪm", eg: "The president will proclaim the new law.", "egzh": "总统将宣布新法律。", "feat": "动词" },
    { word: "reclaim", zh: "收回|取回|拿回|开垦", soundmark: "rɪˈkleɪm", eg: "The company will try to reclaim the lost profits.", "egzh": "公司将试图收回失去的利润。", "feat": "动词" },
    { word: "civil", zh: "文明的，公民的", soundmark: "ˈsɪvəl", eg: "Civil rights are fundamental to a democratic society.", "egzh": "公民权利对于一个民主社会是基本的。", "feat": "adj" },
    { word: "civilian", zh: "平民，百姓", soundmark: "sɪˈvɪliən", eg: "The area is open to both military and civilian personnel.", "egzh": "该地区对军人和平民都开放。", "feat": "n" },
    { word: "civilize", zh: "使文明化", soundmark: "ˈsɪvəlaɪz", eg: "The mission was to civilize the native tribes.", "egzh": "使命是使土著部落文明化。", "feat": "v" },
    { word: "civilization", zh: "文明", soundmark: "ˌsɪvəlaɪˈzeɪʃən", eg: "The ancient civilization left behind many cultural artifacts.", "egzh": "古代文明留下了许多文化遗产。", "feat": "n" },
    { word: "citizen", zh: "公民，市民", soundmark: "ˈsɪtɪzn̩", eg: "Every citizen has the right to vote.", "egzh": "每个公民都有投票的权利。", "feat": "n" },
    { word: "incline", zh: "倾斜，倾向", soundmark: "ɪnˈklaɪn", eg: "The road inclines steeply as it reaches the summit.", "egzh": "道路在到达山顶时倾斜得很陡。", "feat": "v/n" },
    { word: "decline", zh: "下降，拒绝", soundmark: "dɪˈklaɪn", eg: "The company experienced a decline in profits last quarter.", "egzh": "公司上个季度利润下降。", "feat": "v/n" },
    { word: "clinic", zh: "诊所", soundmark: "ˈklɪnɪk", eg: "I have an appointment at the dental clinic tomorrow.", "egzh": "我明天在牙科诊所有个预约。", "feat": "n" },
    { word: "climax", zh: "高潮，顶点", soundmark: "ˈklaɪmæks", eg: "The movie reaches its climax in the final scenes.", "egzh": "电影在最后几场达到高潮。", "feat": "n" },
    { word: "climate", zh: "气候，气氛", soundmark: "ˈklaɪmət", eg: "The climate in this region is hot and humid.", "egzh": "这个地区的气候又热又湿。", "feat": "n" },
    { word: "acclimatize", zh: "使适应新环境", soundmark: "əˈklaɪməˌtaɪz", eg: "It takes time to acclimatize to a different climate.", "egzh": "适应不同气候需要时间。", "feat": "v" },
    { word: "acclimation", zh: "适应新环境", soundmark: "əˌklaɪˈmeɪʃən", eg: "Acclimation to high altitudes is challenging for some people.", "egzh": "对高海拔环境的适应对一些人来说是具有挑战性的。", "feat": "n" },
    { word: "closet", zh: "壁橱，密室", soundmark: "ˈklɑːzɪt", eg: "She found the missing keys in the closet.", "egzh": "她在壁橱里找到了丢失的钥匙。", "feat": "n" },
    { word: "enclose", zh: "围绕，附上", soundmark: "ɪnˈkloʊz", eg: "Please enclose a check with your application.", "egzh": "请在申请中附上支票。", "feat": "v" },
    { word: "enclosure", zh: "围场，围墙", soundmark: "ɪnˈkloʊʒər", eg: "The farmer built an enclosure for his sheep.", "egzh": "农民为他的羊建了一个围场。", "feat": "n" },
    { word: "disclose", zh: "揭露，透露", soundmark: "dɪsˈkloʊz", eg: "The company is required to disclose financial information.", "egzh": "公司有责任公开财务信息。", "feat": "v" },
    { word: "inclusive", zh: "包括一切的", soundmark: "ɪnˈkluːsɪv", eg: "The hotel offers an all-inclusive vacation package.", "egzh": "这家酒店提供一揽子度假套餐。", "feat": "adj" },
    { word: "exclusive", zh: "独家的，排他的", soundmark: "ɪkˈskluːsɪv", eg: "The store sells exclusive designer clothing.", "egzh": "这家商店销售独家的设计师服装。", "feat": "adj" },
    { word: "conclude", zh: "结束，得出结论", soundmark: "kənˈkluːd", eg: "Let's conclude the meeting with some final remarks.", "egzh": "让我们以一些最后的话结束会议。", "feat": "v" },
    { word: "conclusion", zh: "结论，结束", soundmark: "kənˈkluːʒən", eg: "The report presents a clear conclusion.", "egzh": "这份报告提出了明确的结论。", "feat": "n" },
    { word: "preclude", zh: "预先排除，阻止", soundmark: "prɪˈkluːd", eg: "His lack of experience may preclude him from the job.", "egzh": "他缺乏经验可能会阻止他获得这份工作。", "feat": "v" },
    { word: "discreet", zh: "慎重的", soundmark: "[dɪˈskrit]", eg: "He is known for being discreet in his business dealings.", egzh: "他以在业务往来中慎重而著称。", feat: "adjective" },
    { word: "concern", zh: "关心", soundmark: "[kənˈsɜrn]", eg: "I concern myself with environmental issues.", egzh: "我关心环境问题。", feat: "verb" },
    { word: "discern", zh: "辨别", soundmark: "[dɪˈsɜrn]", eg: "It's difficult to discern the truth from the rumors.", egzh: "很难从谣言中辨别出真相。", feat: "verb" },
    { word: "accord", zh: "协议，符合，调和", soundmark: "əˈkɔrd", eg: "The two sides reached an accord on the trade agreement.", "egzh": "双方就贸易协议达成了一致。", "feat": "n/v" },
    { word: "accordance", zh: "一致，调和", soundmark: "əˈkɔrdəns", eg: "In accordance with the law, the company must pay taxes.", "egzh": "根据法律规定，公司必须支付税款。", "feat": "n" },
    { word: "according", zh: "根据", soundmark: "əˈkɔrdɪŋ", eg: "According to the weather forecast, it will rain tomorrow.", "egzh": "根据天气预报，明天会下雨。", "feat": "prep" },
    { word: "accordingly", zh: "因此，相应地", soundmark: "əˈkɔrdɪŋli", eg: "He was busy, and accordingly, he couldn't attend the meeting.", "egzh": "他很忙，因此他不能参加会议。", "feat": "adv" },
    { word: "record", zh: "记录，唱片", soundmark: "ˈrekərd", eg: "She keeps a record of her expenses.", "egzh": "她记载了她的开支。", "feat": "n/v" },
    { word: "recorder", zh: "录音机，记录员", soundmark: "rɪˈkɔrdər", eg: "The recorder allows you to capture audio.", "egzh": "录音机允许你录制音频。", "feat": "n" },
    { word: "cordial", zh: "热诚的，亲切的", soundmark: "ˈkɔrdiəl", eg: "She received a cordial welcome from her new colleagues.", "egzh": "她受到了新同事们的热情欢迎。", "feat": "adj" },
    { word: "count", zh: "计数，数数", soundmark: "kaʊnt", eg: "Please count the number of items in the inventory.", "egzh": "请数清库存中的物品数量。", "feat": "v/n" },
    { word: "counter", zh: "柜台，反对，对立", soundmark: "ˈkaʊntər", eg: "She placed her keys on the counter.", "egzh": "她把钥匙放在柜台上。", "feat": "n/v" },
    { word: "discount", zh: "折扣，打折", soundmark: "ˈdɪskaʊnt", eg: "You can get a discount on this product during the sale.", "egzh": "在促销期间，你可以享受这个产品的折扣。", "feat": "n/v" },
    { word: "account", zh: "账户，解释，计算", soundmark: "əˈkaʊnt", eg: "She checked her bank account online.", "egzh": "她在线查看了她的银行账户。", "feat": "n/v" },
    { word: "accountant", zh: "会计师", soundmark: "əˈkaʊntənt", eg: "The accountant prepared the financial statements.", "egzh": "会计师准备了财务报表。", "feat": "n" },
    { word: "cover", zh: "覆盖，封面，保险", soundmark: "ˈkʌvər", eg: "The blanket will cover you and keep you warm.", "egzh": "毯子会盖住你，保暖。", "feat": "v/n" },
    { word: "uncover", zh: "揭开，发现", soundmark: "ʌnˈkʌvər", eg: "The archaeologists uncovered an ancient tomb.", "egzh": "考古学家发掘出一个古墓。", "feat": "v" },
    { word: "discover", zh: "发现，发觉", soundmark: "dɪsˈkʌvər", eg: "She discovered a hidden treasure in the old attic.", "egzh": "她在老阁楼里发现了一个隐藏的宝藏。", "feat": "v" },
    { word: "recover", zh: "恢复，康复", soundmark: "rɪˈkʌvər", eg: "He is expected to recover from his illness soon.", "egzh": "他预计很快会从疾病中康复。", "feat": "v" },
    { word: "increase", zh: "增加，增长", soundmark: "ɪnˈkris", eg: "The company plans to increase its production capacity.", "egzh": "公司计划增加生产能力。", "feat": "v/n" },
    { word: "increasingly", zh: "越来越，日益", soundmark: "ɪnˈkrisɪŋli", eg: "The demand for clean energy is increasing increasingly.", "egzh": "对清洁能源的需求正在日益增加。", "feat": "adv" },
    { word: "decrease", zh: "减少，下降", soundmark: "dɪˈkris", eg: "There has been a decrease in the price of oil.", "egzh": "石油价格已经下降。", "feat": "v/n" },
    { word: "create", zh: "创建，创造", soundmark: "kriˈeɪt", eg: "She used her artistic skills to create a beautiful painting.", "egzh": "她运用她的艺术技巧创作了一幅美丽的画。", "feat": "v" },
    { word: "creative", zh: "创造性的，有创意的", soundmark: "kriˈeɪtɪv", eg: "The creative team brainstormed new ideas for the project.", "egzh": "创意团队为项目进行了头脑风暴，提出了新的创意。", "feat": "adj" },
    { word: "creation", zh: "创造，创作物", soundmark: "kriˈeɪʃən", eg: "The artist's latest creation is a masterpiece.", "egzh": "这位艺术家最新的创作是杰作。", "feat": "n" },
    { word: "creature", zh: "生物，动物", soundmark: "ˈkriːtʃər", eg: "The forest is home to many different creatures.", "egzh": "森林是许多不同生物的家园。", "feat": "n" },
    { word: "concrete", zh: "混凝土，具体的", soundmark: "ˈkɑnkriːt", eg: "The building is made of concrete.", "egzh": "这座建筑是用混凝土建造的。", "feat": "n/adj" },
    { word: "credit", zh: "信用，赞扬", soundmark: "ˈkrɛdɪt", eg: "She has good credit and can get a loan easily.", "egzh": "她信用良好，可以轻松获得贷款。", "feat": "n/v" },
    { word: "credible", zh: "可信的，可靠的", soundmark: "ˈkrɛdəbl", eg: "The witness gave a credible account of the incident.", "egzh": "证人提供了一个可信的事件描述。", "feat": "adj" },
    { word: "credential", zh: "证件，资格证书", soundmark: "krɪˈdɛnʃəl", eg: "You need to show your credentials to access the secure area.", "egzh": "你需要出示你的证件才能进入安全区域。", "feat": "n" },
    { word: "colony", zh: "殖民地，群体", soundmark: "ˈkɑləni", eg: "The British established a colony in America in the 17th century.", "egzh": "17世纪英国在美洲建立了一个殖民地。", "feat": "n" },
    { word: "culture", zh: "文化，培养", soundmark: "ˈkʌltʃər", eg: "This museum showcases the culture of ancient civilizations.", "egzh": "这家博物馆展示了古代文明的文化。", "feat": "n/v" },
    { word: "agriculture", zh: "农业", soundmark: "ˈæɡrɪˌkʌltʃər", eg: "Agriculture plays a vital role in the country's economy.", "egzh": "农业在该国经济中起着至关重要的作用。", "feat": "n" },
    { word: "cultivate", zh: "耕种，培养", soundmark: "ˈkʌltəˌveɪt", eg: "Farmers cultivate crops in the fields.", "egzh": "农民在田地里耕种庄稼。", "feat": "v" },
    { word: "crime", "zh": "犯罪，罪行", soundmark: "kraɪm", eg: "The police are investigating the crime.", "egzh": "警察正在调查这起犯罪案件。", "feat": "n" },
    { word: "criminal", "zh": "犯罪的，罪犯", soundmark: "ˈkrɪmɪnl", eg: "The judge sentenced the criminal to ten years in prison.", "egzh": "法官判处罪犯十年监禁。", "feat": "adj/n" },
    { word: "discriminate", "zh": "歧视，区别对待", soundmark: "dɪˈskrɪmɪˌneɪt", eg: "It is important not to discriminate against people based on their race or ethnicity.", "egzh": "重要的是不要因为种族或族裔而歧视人们。", "feat": "v" },
    { word: "criterion", "zh": "标准，准则", soundmark: "kraɪˈtɪriən", eg: "The criteria for selecting a candidate include experience and qualifications.", "egzh": "选择候选人的标准包括经验和资格。", "feat": "n" },
    { word: "critic", "zh": "批评家，评论家", soundmark: "ˈkrɪtɪk", eg: "The film received mixed reviews from critics.", "egzh": "这部电影在评论家中获得了褒贬不一的评价。", "feat": "n" },
    { word: "critical", "zh": "关键的，批评的", soundmark: "ˈkrɪtɪkl", eg: "His critical analysis of the situation was very helpful.", "egzh": "他对局势的批判性分析非常有帮助。", "feat": "adj" },
    { word: "criticism", "zh": "批评，批判", soundmark: "ˈkrɪtɪsɪzəm", eg: "She was open to constructive criticism to improve her work.", "egzh": "她愿意接受建设性的批评以改进自己的工作。", "feat": "n" },
    { word: "criticize", "zh": "批评，指责", soundmark: "ˈkrɪtɪˌsaɪz", eg: "It's important to be able to criticize your own work to make it better.", "egzh": "能够批评自己的工作以使其更好是重要的。", "feat": "v" },
    { word: "occur", "zh": "发生，出现", soundmark: "əˈkɜːr", eg: "The accident occurred on the highway.", "egzh": "事故发生在高速公路上。", "feat": "v" },
    { word: "occurrence", "zh": "事件，发生", soundmark: "əˈkɜːrəns", eg: "The occurrence of earthquakes in this region is not uncommon.", "egzh": "这个地区地震的发生并不罕见。", "feat": "n" },
    { word: "current", "zh": "电流，流动的", soundmark: "ˈkɜːrənt", eg: "The current in the river is very strong.", "egzh": "这条河中的水流很强。", "feat": "n/adj" },
    { word: "currency", "zh": "货币，通货", soundmark: "ˈkɜːrənsi", eg: "The euro is a common currency in many European countries.", "egzh": "欧元是许多欧洲国家的通货。", "feat": "n" },
    { word: "recur", "zh": "重复发生，再次发生", soundmark: "rɪˈkɜːr", eg: "The same issue tends to recur in our discussions.", "egzh": "相同的问题在我们的讨论中往往会再次出现。", "feat": "v" },
    { word: "course", "zh": "课程，过程", soundmark: "kɔːrs", eg: "I'm taking a French course at the community college.", "egzh": "我在社区大学上法语课程。", "feat": "n" },
    { word: "discourse", "zh": "话语，演讲", soundmark: "ˈdɪskɔːrs", eg: "The professor delivered a discourse on the topic of ethics.", "egzh": "教授就伦理学话题发表了演讲。", "feat": "n" },
    { word: "cure", "zh": "治疗，治愈", soundmark: "kjʊr", eg: "The new medicine can cure the common cold.", "egzh": "这种新药可以治愈普通感冒。", "feat": "v/n" },
    { word: "curious", "zh": "好奇的，奇怪的", soundmark: "ˈkjʊriəs", eg: "Children are naturally curious about the world around them.", "egzh": "孩子们自然对他们周围的世界充满好奇。", "feat": "adj" },
    { word: "curiosity", "zh": "好奇心，奇事", soundmark: "ˌkjʊriˈɑːsəti", eg: "The discovery of the ancient artifact piqued our curiosity.", "egzh": "古代文物的发现激起了我们的好奇心。", "feat": "n" },
    { word: "secure", "zh": "安全的，确保，获得", soundmark: "sɪˈkjʊr", eg: "They need to secure their home to prevent break-ins.", "egzh": "他们需要保障家庭安全以防止入室盗窃。", "feat": "adj/v" },
    { word: "security", "zh": "安全，保障", soundmark: "sɪˈkjʊrəti", eg: "Airport security is an important concern for travelers.", "egzh": "机场安全是旅行者的重要关切。", "feat": "n" },
    { word: "bicycle", "zh": "自行车", soundmark: "ˈbaɪsɪkl", eg: "I ride my bicycle to work every day.", "egzh": "我每天骑自行车上班。", "feat": "n" },
    { word: "cycle", "zh": "周期，骑自行车", soundmark: "ˈsaɪkl", eg: "The water cycle is a natural process.", "egzh": "水循环是一个自然过程。", "feat": "n/v" },
    { word: "recycle", "zh": "回收利用", soundmark: "riˈsaɪkl", eg: "It's important to recycle paper and plastic to reduce waste.", "egzh": "回收纸张和塑料以减少废物是很重要的。", "feat": "v" },
    { word: "encyclopedia", "zh": "百科全书，百科全书式的", soundmark: "ɪnˌsaɪkləˈpiːdiə", eg: "I found the information in an encyclopedia.", "egzh": "我在百科全书中找到了这些信息。", "feat": "n/adj" },
    { word: "democracy", "zh": "民主，民主制度", soundmark: "dɪˈmɑːkrəsi", eg: "Many countries around the world practice democracy.", "egzh": "世界上许多国家实行民主制度。", "feat": "n" },
    { word: "democratic", "zh": "民主的，民主政体的", soundmark: "ˌdɛməˈkrætɪk", eg: "The nation held democratic elections.", "egzh": "该国举行了民主选举。", "feat": "adj" },
    { word: "epidemic", "zh": "流行病，传染病", soundmark: "ˌɛpɪˈdɛmɪk", eg: "The city faced a flu epidemic last winter.", "egzh": "该城市在去年冬季爆发了流感流行病。", "feat": "n" },
    { word: "indicate", "zh": "指示，表明", soundmark: "ˈɪndɪˌkeɪt", eg: "The signs indicate the way to the exit.", "egzh": "标志指示通往出口的路。", "feat": "v" },
    { word: "indication", "zh": "迹象，指示", soundmark: "ˌɪndɪˈkeɪʃən", eg: "The high temperature is an indication of fever.", "egzh": "高烧是发热的迹象。", "feat": "n" },
    { word: "indicator", "zh": "指示器，标志", soundmark: "ˈɪndɪˌkeɪtər", eg: "The red light is an indicator of danger.", "egzh": "红灯是危险的指示器。", "feat": "n" },
    { word: "dictate", "zh": "口授，命令", soundmark: "ˈdɪkteɪt", eg: "The boss will dictate the letter, and I will type it.", "egzh": "老板会口授这封信，我会打字。", "feat": "v" },
    { word: "dictation", "zh": "听写，口述", soundmark: "dɪkˈteɪʃən", eg: "The teacher gave us a dictation to test our spelling.", "egzh": "老师给我们听写考察拼写能力。", "feat": "n" },
    { word: "dictionary", "zh": "词典，字典", soundmark: "ˈdɪkʃəˌnɛri", eg: "I use a dictionary to look up unfamiliar words.", "egzh": "我用词典查找生词。", "feat": "n" },
    { word: "contradict", "zh": "反驳，否认", soundmark: "ˌkɑntrəˈdɪkt", eg: "She will contradict your statement if she disagrees.", "egzh": "如果她不同意，她会反驳你的陈述。", "feat": "v" },
    { word: "contradiction", "zh": "矛盾，反驳", soundmark: "ˌkɑntrəˈdɪkʃən", eg: "There is a contradiction between what he said and what he did.", "egzh": "他说的话和他的行为之间存在矛盾。", "feat": "n" },
    { word: "predict", "zh": "预测，预言", soundmark: "prɪˈdɪkt", eg: "Scientists predict that the weather will improve tomorrow.", "egzh": "科学家预测明天天气会好转。", "feat": "v" },
    { word: "prediction", "zh": "预测，预言", soundmark: "prɪˈdɪkʃən", eg: "Her prediction about the stock market turned out to be accurate.", "egzh": "她关于股市的预测结果准确。", "feat": "n" },
    { word: "conduct", "zh": "行为，举止", soundmark: "ˈkɑndʌkt", eg: "His conduct during the meeting was unprofessional.", "egzh": "他在会议期间的行为不专业。", "feat": "n/v" },
    { word: "educate", "zh": "教育，培养", soundmark: "ˈɛdjuˌkeɪt", eg: "Parents have a responsibility to educate their children.", "egzh": "父母有责任教育他们的孩子。", "feat": "v" },
    { word: "education", "zh": "教育，教育系统", soundmark: "ˌɛdʒuˈkeɪʃən", eg: "The education system in this country is highly regarded.", "egzh": "这个国家的教育系统备受尊敬。", "feat": "n" },
    { word: "introduce", "zh": "介绍，引入", soundmark: "ˌɪntrəˈdjuːs", eg: "Allow me to introduce myself.", "egzh": "请允许我自我介绍。", "feat": "v" },
    { word: "introduction", "zh": "介绍，引言", soundmark: "ˌɪntrəˈdʌkʃən", eg: "The introduction of the book provides context for the story.", "egzh": "书的引言为故事提供了背景。", "feat": "n" },
    { word: "deduce", "zh": "推断，演绎", soundmark: "dɪˈduːs", eg: "We can deduce the answer from the available information.", "egzh": "我们可以从现有的信息中推断出答案。", "feat": "v" },
    { word: "induce", "zh": "诱导，引起", soundmark: "ɪnˈduːs", eg: "The advertisement is designed to induce consumers to buy the product.", "egzh": "广告旨在诱导消费者购买该产品。", "feat": "v" },
    { word: "dominate", "zh": "主导，统治", soundmark: "ˈdɑməˌneɪt", eg: "The team continued to dominate the competition.", "egzh": "这支队伍继续主导比赛。", "feat": "v" },
    { word: "predominate", "zh": "占主导地位", soundmark: "prɪˈdɑməˌneɪt", eg: "The forest is populated by trees, and they predominate in the landscape.", "egzh": "森林中到处都是树木，它们占据了主导地位。", "feat": "v" },
    { word: "dominant", "zh": "占优势的，主导的", soundmark: "ˈdɑmənənt", eg: "The dominant theme of the conference was environmental sustainability.", "egzh": "会议的主导主题是环境可持续性。", "feat": "adj" },
    { word: "durable", "zh": "耐用的，持久的", soundmark: "ˈdʊrəbl", eg: "This material is known for being durable and long-lasting.", "egzh": "这种材料以耐用和持久而闻名。", "feat": "adj" },
    { word: "duration", "zh": "持续时间，期间", soundmark: "djuˈreɪʃən", eg: "The duration of the movie is two hours.", "egzh": "这部电影的持续时间为两小时。", "feat": "n" },
    { word: "during", "zh": "在...期间，时期", soundmark: "ˈdʊrɪŋ", eg: "I met her during my time in college.", "egzh": "我在大学时期认识她。", "feat": "prep" },
    { word: "endure", "zh": "忍受，持久", soundmark: "ɪnˈdʊr", eg: "She had to endure difficult conditions during the expedition.", "egzh": "她不得不在探险期间忍受困难的条件。", "feat": "v" },
    { word: "endurance", "zh": "耐力，忍耐力", soundmark: "ɪnˈdʊrəns", eg: "Marathon runners need a lot of endurance.", "egzh": "马拉松选手需要很强的耐力。", "feat": "n" },
    { word: "exempt", "zh": "免除，豁免", soundmark: "ɪgˈzɛmpt", eg: "Some students are exempt from taking the final exam.", "egzh": "一些学生可以免修期末考试。", "feat": "v/adj" },
    { word: "prompt", "zh": "迅速的，促使", soundmark: "prɑmpt", eg: "His prompt response to the emergency saved lives.", "egzh": "他对紧急情况的迅速反应挽救了生命。", "feat": "adj/v" },
    { word: "adequate", "zh": "足够的，适当的", soundmark: "ˈædɪkwət", eg: "The supplies were adequate to meet the demand.", "egzh": "供应品足够满足需求。", "feat": "adj" },
    { word: "adequacy", "zh": "充分，适当", soundmark: "ˈædɪkwəsi", eg: "The adequacy of the training program is being assessed.", "egzh": "正在评估培训计划的充分性。", "feat": "n" },
    { word: "adequately", "zh": "充分地，适当地", soundmark: "ˈædɪkwətli", eg: "The issue was adequately addressed in the report.", "egzh": "这个问题在报告中得到了充分处理。", "feat": "adv" },
    { word: "inadequate", "zh": "不足的，不适当的", soundmark: "ɪnˈædɪkwət", eg: "The current resources are inadequate for the task.", "egzh": "目前的资源不足以完成任务。", "feat": "adj" },
    { word: "equal", "zh": "相等的，平等的", soundmark: "ˈikwəl", eg: "All citizens should be treated as equals under the law.", "egzh": "所有公民应该在法律面前被视为平等。", "feat": "adj" },
    { word: "equality", "zh": "平等，平等性", soundmark: "ɪˈkwɑləti", eg: "The fight for gender equality continues.", "egzh": "性别平等的斗争仍在继续。", "feat": "n" },
    { word: "equate", "zh": "等同，相等", soundmark: "ɪˈkwet", eg: "Some people equate success with happiness.", "egzh": "有些人将成功等同于幸福。", "feat": "v" },
    { word: "equation", "zh": "方程，等式", soundmark: "ɪˈkweʃən", eg: "Solving the equation requires algebraic skills.", "egzh": "解方程需要代数技能。", "feat": "n" },
    { word: "equator", "zh": "赤道", soundmark: "ɪˈkweɪtər", eg: "The equator divides the Earth into two hemispheres.", "egzh": "赤道将地球分为两个半球。", "feat": "n" },
    { word: "equivalent", "zh": "相等的，等值的", soundmark: "ɪˈkwɪvələnt", eg: "These two products are roughly equivalent in quality.", "egzh": "这两种产品在质量上大致相等。", "feat": "adj/n" },
    { word: "essence", "zh": "本质，精髓", soundmark: "ˈɛsəns", eg: "The essence of the argument lies in this key point.", "egzh": "争论的本质在于这一关键点。", "feat": "n" },
    { word: "essential", "zh": "必要的，基本的", soundmark: "ɪˈsɛnʃəl", eg: "Water is essential for human survival.", "egzh": "水对人类生存是必要的。", "feat": "adj/n" },
    { word: "absent", "zh": "缺席的，不在场的", soundmark: "ˈæbsənt", eg: "She was absent from the meeting due to illness.", "egzh": "她因病未能出席会议。", "feat": "adj" },
    { word: "absence", "zh": "缺席，不在场", soundmark: "ˈæbsəns", eg: "His absence was noticed by everyone in the room.", "egzh": "大家都注意到了他的缺席。", "feat": "n" },
    { word: "present", "zh": "出席的，礼物，目前", soundmark: "ˈprɛzənt", eg: "He is present at the conference.", "egzh": "他出席了会议。", "feat": "adj/n/v" },
    { word: "presence", "zh": "出席，存在", soundmark: "ˈprɛzəns", eg: "His presence in the room was imposing.", "egzh": "他在房间里的存在令人印象深刻。", "feat": "n" },
    { word: "presently", "zh": "目前，不久后", soundmark: "ˈprɛzəntli", eg: "She will be here presently.", "egzh": "她不久就会到这里。", "feat": "adv" },
    { word: "interest", "zh": "兴趣，利息", soundmark: "ˈɪntrəst", eg: "His interest in science led to a career in research.", "egzh": "他对科学的兴趣导致了从事研究的职业。", "feat": "n/v" },
    { word: "interesting", "zh": "有趣的，引人入胜的", soundmark: "ˈɪntrəstɪŋ", eg: "The lecture was interesting and informative.", "egzh": "这场讲座既有趣又富有信息。", "feat": "adj" },
    { word: "estimate", "zh": "估计、估算", soundmark: "/ˈɛstɪˌmeɪt/", "eg": "Can you estimate the cost of the project?", "egzh": "你能估算一下这个项目的成本吗？", "feat": "n." },
    { word: "underestimate", "zh": "低估、轻视", soundmark: "/ˌʌndərˈɛstɪˌmeɪt/", "eg": "Don't underestimate the challenges of this task.", "egzh": "不要低估这项任务的挑战。", "feat": "v." },
    { word: "esteem", "zh": "尊敬、尊重", soundmark: "/ɪsˈtiːm/", "eg": "She is held in high esteem by her colleagues.", "egzh": "她在同事中备受尊敬。", "feat": "v." },
    { word: "facile", "zh": "轻松的、容易的", soundmark: "/ˈfæsaɪl/", "eg": "His facile answers made him a popular guest on the talk show.", "egzh": "他轻松的回答使他成为脱口秀节目上受欢迎的嘉宾。", "feat": "adj." },
    { word: "facility", "zh": "设施、设备", soundmark: "/fəˈsɪləti/", "eg": "The gym has excellent facilities for exercise.", "egzh": "健身房设有出色的锻炼设施。", "feat": "n." },
    { word: "facilitate", "zh": "促进、使便利", soundmark: "/fəˈsɪlɪˌteɪt/", "eg": "The new technology will facilitate communication.", "egzh": "新技术将促进交流。", "feat": "v." },
    { word: "faculty", "zh": "学院、才能、能力、天赋", soundmark: "/ˈfækəlti/", "eg": "She is a member of the faculty at the university.", "egzh": "她是大学的一名教职工。", "feat": "n." },
    { word: "fact", "zh": "事实、实际", soundmark: "/fækt/", "eg": "The fact is, we need to make a decision soon.", "egzh": "事实是，我们需要尽快做出决定。", "feat": "n." },
    { word: "factor", "zh": "因素、因子", soundmark: "/ˈfæktər/", "eg": "Many factors contribute to the success of a business.", "egzh": "许多因素有助于企业的成功。", "feat": "n." },
    { word: "factory", "zh": "工厂、制造厂", soundmark: "/ˈfæktri/", "eg": "The factory produces cars for export.", "egzh": "这家工厂生产出口用的汽车。", "feat": "n." },
    { word: "affect", "zh": "影响、感动", soundmark: "/əˈfɛkt/", "eg": "How does stress affect your health?", "egzh": "压力如何影响你的健康？", "feat": "v." },
    { word: "affection", "zh": "感情、喜爱", soundmark: "/əˈfɛkʃən/", "eg": "She showed great affection for her pet dog.", "egzh": "她对她的宠物狗表现出极大的喜爱。", "feat": "n." },
    { word: "effect", "zh": "效果、影响", soundmark: "/ɪˈfɛkt/", "eg": "The medication had a positive effect on his condition.", "egzh": "这种药物对他的病情有积极的影响。", "feat": "n." },
    { word: "effective", "zh": "有效的、生效的", soundmark: "/ɪˈfɛktɪv/", "eg": "The new law will be effective starting next month.", "egzh": "新法律将从下个月开始生效。", "feat": "adj." },
    { word: "defect", "zh": "缺陷、缺点", soundmark: "/dɪˈfɛkt/", "eg": "The product had a minor defect that needed fixing.", "egzh": "该产品有一个需要修复的小缺陷。", "feat": "n." },
    { word: "infect", "zh": "感染、传染", soundmark: "/ɪnˈfɛkt/", "eg": "The virus can infect humans and animals.", "egzh": "这种病毒能感染人类和动物。", "feat": "v." },
    { word: "infectious", "zh": "传染的、有感染力的", soundmark: "/ɪnˈfɛkʃəs/", "eg": "Her laughter was infectious, and soon everyone was laughing.", "egzh": "她的笑声有感染力，很快每个人都笑了起来。", "feat": "adj." },
    { word: "perfect", "zh": "完美的、完善的", soundmark: "/ˈpɜːfɪkt/", "eg": "She has a perfect score on the test.", "egzh": "她在考试中获得了满分。", "feat": "adj." },
    { word: "perfection", "zh": "完美、完善", soundmark: "/pəˈfɛkʃən/", "eg": "He strived for perfection in his work.", "egzh": "他在工作中追求完美。", "feat": "n." },
    { word: "profit", "zh": "利润、盈利", soundmark: "/ˈprɒfɪt/", "eg": "The company made a significant profit this quarter.", "egzh": "公司本季度取得了显著的盈利。", "feat": "n." },
    { word: "profitable", "zh": "有利可图的、赚钱的", soundmark: "/ˈprɒfɪtəbl/", "eg": "Investing in that business turned out to be highly profitable.", "egzh": "投资那家企业最终证明是非常有利可图的。", "feat": "adj." },
    { word: "feat", "zh": "壮丽的业绩、技艺", soundmark: "/fiːt/", "eg": "Climbing that mountain was a remarkable feat.", "egzh": "攀登那座山是一项令人印象深刻的壮丽业绩。", "feat": "n." },
    { word: "efficient", "zh": "高效的、有效的", soundmark: "/ɪˈfɪʃənt/", "eg": "The new machinery made the production process more efficient.", "egzh": "新机器使生产过程更加高效。", "feat": "adj." },
    { word: "efficiency", "zh": "效率、效能", soundmark: "/ɪˈfɪʃənsi/", "eg": "Improving efficiency is a key goal for this project.", "egzh": "提高效率是这个项目的一个关键目标。", "feat": "n." },
    { word: "deficient", "zh": "不足的、有缺陷的", soundmark: "/dɪˈfɪʃənt/", "eg": "The report identified several deficient areas in the company's operations.", "egzh": "报告确定了公司运营中的几个不足之处。", "feat": "adj." },
    { word: "deficienty", "zh": "缺陷、不足", soundmark: "/dɪˈfɪʃənti/", "eg": "The deficienty in the product design led to many customer complaints.", "egzh": "产品设计的不足导致了许多客户投诉。", "feat": "n." },
    { word: "difficult", "zh": "困难的、艰难的", soundmark: "/ˈdɪfɪkəlt/", "eg": "Learning a new language can be difficult, but it's rewarding.", "egzh": "学习一门新语言可能很困难，但很有回报。", "feat": "adj." },
    { word: "difficulty", "zh": "困难、难题", soundmark: "/ˈdɪfɪkəlti/", "eg": "Overcoming this difficulty required a lot of effort.", "egzh": "克服这个困难需要付出很大的努力。", "feat": "n." },
    { word: "magnificent", "zh": "壮丽的、宏伟的", soundmark: "/mæɡˈnɪfɪsənt/", "eg": "The view from the mountaintop was absolutely magnificent.", "egzh": "从山顶上的景色绝对壮丽。", "feat": "adj." },
    { word: "magnificence", "zh": "壮丽、宏伟", soundmark: "/mæɡˈnɪfɪsəns/", "eg": "The magnificence of the palace was beyond description.", "egzh": "宫殿的壮丽程度无法描述。", "feat": "n." },
    { word: "significant", "zh": "重要的、有意义的", soundmark: "/sɪɡˈnɪfɪkənt/", "eg": "The discovery of a new species is a significant event for scientists.", "egzh": "发现新物种对科学家来说是一件重要的事件。", "feat": "adj." },
    { word: "significance", "zh": "重要性、意义", soundmark: "/sɪɡˈnɪfɪkəns/", "eg": "The significance of this historical site cannot be overstated.", "egzh": "这个历史遗址的重要性不可言喻。", "feat": "n." },
    { word: "signify", "zh": "表示、意味着", soundmark: "/ˈsɪɡnɪfaɪ/", "eg": "His silence could signify his disagreement.", "egzh": "他的沉默可能表示他的不同意。", "feat": "v." },
    { word: "proficient", "zh": "熟练的、精通的", soundmark: "/prəˈfɪʃənt/", "eg": "She is proficient in several programming languages.", "egzh": "她精通多种编程语言。", "feat": "adj." },
    { word: "proficienty", "zh": "熟练、精通", soundmark: "/prəˈfɪʃənti/", "eg": "His proficienty in mathematics impressed his teachers.", "egzh": "他在数学方面的精通让老师们印象深刻。", "feat": "n." },
    { word: "suffice", "zh": "足够、满足需要", soundmark: "/səˈfaɪs/", "eg": "A simple apology may suffice to mend the relationship.", "egzh": "简单的道歉可能足够修复关系。", "feat": "v." },
    { word: "sufficient", "zh": "足够的、充足的", soundmark: "/səˈfɪʃənt/", "eg": "We have sufficient evidence to prove our case.", "egzh": "我们有足够的证据来证明我们的案子。", "feat": "adj." },
    { word: "sufficiency", "zh": "足够、充分", soundmark: "/səˈfɪʃənsi/", "eg": "The sufficiency of food and water is crucial in a survival situation.", "egzh": "在生存状况下，食物和水的充足是至关重要的。", "feat": "n." },
    { word: "office", "zh": "办公室、公务员", soundmark: "/ˈɒfɪs/", "eg": "I'll meet you in my office at 2 o'clock.", "egzh": "我会在下午两点在我的办公室见你。", "feat": "n." },
    { word: "official", "zh": "官方的、官员", soundmark: "/əˈfɪʃəl/", "eg": "The official statement confirmed the government's stance.", "egzh": "官方声明确认了政府的立场。", "feat": "adj./n." },
    { word: "officer", "zh": "官员、警察", soundmark: "/ˈɒfɪsər/", "eg": "The police officer helped direct traffic during the parade.", "egzh": "警察官员在游行期间帮助引导交通。", "feat": "n." },
    { word: "beneficial", "zh": "有益的、有利的", soundmark: "/ˌbɛnɪˈfɪʃəl/", "eg": "Exercise is beneficial for both physical and mental health.", "egzh": "锻炼对身体和心理健康都有益。", "feat": "adj." },
    { word: "benefit", "zh": "好处、利益", soundmark: "/ˈbɛnɪfɪt/", "eg": "The company offers many employee benefits, including health insurance.", "egzh": "公司提供许多员工福利，包括健康保险。", "feat": "n." },
    { word: "pacific", "zh": "和平的、太平洋的", soundmark: "/pəˈsɪfɪk/", "eg": "The country has a long history of pacific relations with its neighbors.", "egzh": "这个国家与邻国有着悠久的和平关系历史。", "feat": "adj." },
    { word: "certificate", "zh": "证书、证明", soundmark: "/sərˈtɪfɪkət/", "eg": "He received a certificate of achievement for his academic success.", "egzh": "他因学业成就获得了成就证书。", "feat": "n." },
    { word: "sacrifice", "zh": "牺牲、献祭", soundmark: "/ˈsækrɪfaɪs/", "eg": "She was willing to sacrifice her own interests for the greater good.", "egzh": "她愿意为了更大的利益牺牲自己的利益。", "feat": "v./n." },
    { "word": "interface", "zh": "界面、接口", "soundmark": "/ˈɪntəfeɪs/", "eg": "The new software has a user-friendly interface.", "egzh": "新软件拥有用户友好的界面。", "feat": "n." },
    { "word": "false", "zh": "虚假的、错误的", "soundmark": "/fɔːls/", "eg": "The information in that email is false.", "egzh": "那封电子邮件中的信息是虚假的。", "feat": "adj." },
    { "word": "fail", "zh": "失败、不及格", "soundmark": "/feɪl/", "eg": "I will not fail this exam.", "egzh": "我不会考试不及格的。", "feat": "v." },
    { "word": "refer", "zh": "提及、参考", "soundmark": "/rɪˈfɜːr/", "eg": "You can refer to the user manual for instructions.", "egzh": "你可以参考用户手册获取指导。", "feat": "v." },
    { "word": "final", "zh": "最终的、最后的", "soundmark": "/ˈfaɪnl/", "eg": "This is the final decision.", "egzh": "这是最终决定。", "feat": "adj." },
    { "word": "finally", "zh": "最终、最后", "soundmark": "/ˈfaɪnəli/", "eg": "He finally arrived after a long journey.", "egzh": "经过漫长的旅程，他最终到达了。", "feat": "adv." },
    { "word": "finish", "zh": "完成、结束", "soundmark": "/ˈfɪnɪʃ/", "eg": "I need to finish this project by the deadline.", "egzh": "我需要在截止日期之前完成这个项目。", "feat": "v." },
    { "word": "preface", "zh": "序言、序文", "soundmark": "/ˈpɜːrfeɪs/", "eg": "The author wrote a preface to introduce the book.", "egzh": "作者写了一篇序言来介绍这本书。", "feat": "n." },
    { "word": "surface", "zh": "表面、表层", "soundmark": "/ˈsɜːrfɪs/", "eg": "She cleaned the surface of the table.", "egzh": "她清洁了桌子的表面。", "feat": "n." },
    { "word": "falsity", "zh": "虚伪、错误", "soundmark": "/ˈfɔːlsəti/", "eg": "He was accused of spreading falsity.", "egzh": "他被指控散布虚假信息。", "feat": "n." },
    { "word": "failure", "zh": "失败、不成功", "soundmark": "/ˈfeɪljər/", "eg": "His business venture ended in failure.", "egzh": "他的商业冒险以失败告终。", "feat": "n." },
    { "word": "fame", "zh": "名誉、声誉", "soundmark": "/feɪm/", "eg": "Her talent brought her fame and recognition.", "egzh": "她的才华为她带来了名誉和认可。", "feat": "n." },
    { "word": "famouse", "zh": "著名的、有名的", "soundmark": "/ˈfeɪməs/", "eg": "He is a famous actor in Hollywood.", "egzh": "他是好莱坞著名的演员。", "feat": "adj." },
    { "word": "fancy", "zh": "幻想、想象", "soundmark": "/ˈfænsi/", "eg": "She often indulges in fancy daydreams.", "egzh": "她经常沉溺于幻想的白日梦。", "feat": "v." },
    { "word": "fantasy", "zh": "幻想、幻想作品", "soundmark": "/ˈfæntəsi/", "eg": "He enjoys reading fantasy novels.", "egzh": "他喜欢阅读幻想小说。", "feat": "n." },
    { "word": "fantastic", "zh": "极好的、奇妙的", "soundmark": "/fænˈtæstɪk/", "eg": "The view from the mountain top was fantastic.", "egzh": "山顶上的景色太棒了。", "feat": "adj." },
    { "word": "differ", "zh": "不同、有区别", "soundmark": "/ˈdɪfər/", "eg": "Their opinions differ on this issue.", "egzh": "他们在这个问题上意见不一。", "feat": "v." },
    { "word": "different", "zh": "不同的、不一样的", "soundmark": "/ˈdɪfrənt/", "eg": "Each person has a different perspective.", "egzh": "每个人都有不同的观点。", "feat": "adj." },
    { "word": "difference", "zh": "不同、差异", "soundmark": "/ˈdɪfrəns/", "eg": "There's a big difference between the two products.", "egzh": "这两种产品之间有很大的差异。", "feat": "n." },
    { "word": "indifferent", "zh": "冷漠的、漠不关心的", "soundmark": "/ɪnˈdɪfrənt/", "eg": "She seemed indifferent to the news.", "egzh": "她对这则消息似乎漠不关心。", "feat": "adj." },
    { "word": "differentiate", "zh": "区分、区别", "soundmark": "/ˌdɪfəˈrɛnʃɪeɪt/", "eg": "Can you differentiate between the two brands?", "egzh": "你能区分这两个品牌吗？", "feat": "v." },
    { "word": "offer", "zh": "提供、提出", "soundmark": "/ˈɒfər/", "eg": "He made an offer to buy the house.", "egzh": "他提出要买这所房子。", "feat": "v." },
    { "word": "reference", "zh": "参考、参照", "soundmark": "/ˈrɛfərəns/", "eg": "He provided a reference to support his claim.", "egzh": "他提供了一个参考来支持他的主张。", "feat": "n." },
    { "word": "transfer", "zh": "转移、调动", "soundmark": "/ˈtrænsfər/", "eg": "He requested a transfer to a different department.", "egzh": "他请求调到另一个部门。", "feat": "v." },
    { "word": "figure", "zh": "数字、图形", "soundmark": "/ˈfɪɡər/", "eg": "The figure on the chart represents sales data.", "egzh": "图表上的数字代表销售数据。", "feat": "n." },
    { "word": "fine", "zh": "罚款、好的", "soundmark": "/faɪn/", "eg": "He had to pay a fine for speeding.", "egzh": "他因超速被罚款。", "feat": "n./adj." },
    { "word": "define", "zh": "定义、界定", "soundmark": "/dɪˈfaɪn/", "eg": "Can you define the meaning of this word?", "egzh": "你能定义这个词的意思吗？", "feat": "v." },
    { "word": "definition", "zh": "定义、释义", "soundmark": "/ˌdɛfɪˈnɪʃən/", "eg": "The dictionary provides a clear definition of the word.", "egzh": "字典提供了这个词的清晰定义。", "feat": "n." },
    { "word": "definite", "zh": "明确的、确定的", "soundmark": "/ˈdɛfɪnɪt/", "eg": "We need a definite answer by tomorrow.", "egzh": "我们需要明确的答复，明天之前。", "feat": "adj." },
    { "word": "finance", "zh": "财务、金融", "soundmark": "/ˈfaɪnæns/", "eg": "She works in the field of finance.", "egzh": "她从事金融领域的工作。", "feat": "n." },
    { "word": "financial", "zh": "金融的、财务的", "soundmark": "/faɪˈnænʃəl/", "eg": "They discussed the company's financial situation.", "egzh": "他们讨论了公司的财务状况。", "feat": "adj." },
    { "word": "finite", "zh": "有限的、限定的", "soundmark": "/ˈfaɪnaɪt/", "eg": "Resources are finite and must be managed wisely.", "egzh": "资源是有限的，必须明智管理。", "feat": "adj." },
    { "word": "infinite", "zh": "无限的、无穷的", "soundmark": "/ˈɪnfɪnət/", "eg": "The universe is believed to be infinite.", "egzh": "宇宙被认为是无限的。", "feat": "adj." },
    { "word": "fairy", "zh": "仙女、小精灵", "soundmark": "/ˈfɛəri/", "eg": "The fairy granted him three wishes.", "egzh": "仙女满足了他的三个愿望。", "feat": "n." },
    { "word": "fate", "zh": "命运、命中注定", "soundmark": "/feɪt/", "eg": "They believed in the power of fate.", "egzh": "他们相信命运的力量。", "feat": "n." },
    { "word": "infant", "zh": "婴儿、幼儿", "soundmark": "/ˈɪnfənt/", "eg": "The infant slept soundly in the crib.", "egzh": "婴儿在婴儿床上安稳地睡着了。", "feat": "n." },
    { "word": "confess", "zh": "承认、坦白", "soundmark": "/kənˈfɛs/", "eg": "He finally decided to confess his mistakes.", "egzh": "他最终决定承认自己的错误。", "feat": "v." },
    { "word": "confer", "zh": "授予、商讨", "soundmark": "/kənˈfɜːr/", "eg": "The university will confer degrees at the graduation ceremony.", "egzh": "大学将在毕业典礼上授予学位。", "feat": "v." },
    { "word": "conference", "zh": "会议、研讨会", "soundmark": "/ˈkɒnfərəns/", "eg": "The international conference will be held next week.", "egzh": "国际会议将于下周举行。", "feat": "n." },
    { "word": "infer", "zh": "推断、推论", "soundmark": "/ɪnˈfɜːr/", "eg": "From the evidence, we can infer that he is guilty.", "egzh": "根据证据，我们可以推断他有罪。", "feat": "v." },
    { "word": "inference", "zh": "推断、推论", "soundmark": "/ˈɪnfərəns/", "eg": "The inference drawn from the data was accurate.", "egzh": "从数据中得出的推断是准确的。", "feat": "n." },
    { "word": "prefer", "zh": "更喜欢、宁愿", "soundmark": "/prɪˈfɜːr/", "eg": "I prefer tea to coffee.", "egzh": "我更喜欢茶而不是咖啡。", "feat": "v." },
    { "word": "preference", "zh": "偏爱、喜好", "soundmark": "/ˈprɛfərəns/", "eg": "Her preference is to eat vegetables rather than meat.", "egzh": "她更喜欢吃蔬菜而不是肉。", "feat": "n." },
    { "word": "preferable", "zh": "更可取的、更好的", "soundmark": "/ˈprɛfərəbl/", "eg": "The first option is preferable to the second.", "egzh": "第一个选项比第二个更可取。", "feat": "adj." },
    { "word": "suffer", "zh": "遭受、忍受", "soundmark": "/ˈsʌfər/", "eg": "She had to suffer through a long and painful recovery.", "egzh": "她不得不忍受漫长而痛苦的康复过程。", "feat": "v." },
    { "word": "confidence", "zh": "信心、自信", "soundmark": "/ˈkɒnfɪdəns/", "eg": "Her confidence in her abilities is inspiring.", "egzh": "她对自己能力的信心令人鼓舞。", "feat": "n." },
    { "word": "confidential", "zh": "机密的、保密的", "soundmark": "/ˌkɒnfɪˈdɛnʃəl/", "eg": "This document is confidential and should not be shared.", "egzh": "这份文件是机密的，不应该分享。", "feat": "adj." },
    { "word": "confident", "zh": "自信的、有信心的", "soundmark": "/ˈkɒnfɪdənt/", "eg": "She is confident that she can succeed.", "egzh": "她有信心可以成功。", "feat": "adj." },
    { "word": "fiction", "zh": "虚构、小说", "soundmark": "/ˈfɪkʃən/", "eg": "She enjoys reading science fiction novels.", "egzh": "她喜欢阅读科幻小说。", "feat": "n." },
    { "word": "confine", "zh": "限制、局限", "soundmark": "/kənˈfaɪn/", "eg": "The doctor advised him to confine his activities to avoid further injury.", "egzh": "医生建议他限制活动以避免进一步受伤。", "feat": "v." },
    { "word": "refine", "zh": "提炼、精炼", "soundmark": "/rɪˈfaɪn/", "eg": "The process is used to refine crude oil.", "egzh": "这个过程用于提炼原油。", "feat": "v." },
    { "word": "format", "zh": "格式、版式", "soundmark": "/ˈfɔːrmæt/", "eg": "The document is in PDF format.", "egzh": "这份文件是PDF格式的。", "feat": "n." },
    { "word": "formal", "zh": "正式的、礼仪的", "soundmark": "/ˈfɔːrməl/", "eg": "Please wear formal attire to the event.", "egzh": "请穿正式服装参加活动。", "feat": "adj." },
    { "word": "informal", "zh": "非正式的、随意的", "soundmark": "/ɪnˈfɔːrməl/", "eg": "The meeting will be informal and relaxed.", "egzh": "会议将是非正式和轻松的。", "feat": "adj." },
    { "word": "platform", "zh": "平台、讲台", "soundmark": "/ˈplætfɔːrm/", "eg": "The speaker stood on the platform to address the audience.", "egzh": "演讲者站在讲台上向观众讲话。", "feat": "n." },
    { "word": "inflat", "zh": "充气、膨胀", "soundmark": "/ɪnˈfleɪt/", "eg": "You need to inflate the balloon.", "egzh": "你需要充气气球。", "feat": "v." },
    { "word": "inflation", "zh": "通货膨胀、膨胀", "soundmark": "/ɪnˈfleɪʃən/", "eg": "The inflation rate has been rising steadily.", "egzh": "通货膨胀率一直在稳步上升。", "feat": "n." },
    { "word": "deflate", "zh": "放气、缩小", "soundmark": "/dɪˈfleɪt/", "eg": "You can use a pump to deflate the air mattress.", "egzh": "你可以使用泵来放气床垫。", "feat": "v." },
    { "word": "deflation", "zh": "通货紧缩、缩小", "soundmark": "/dɪˈfleɪʃən/", "eg": "The deflation of the balloon was intentional.", "egzh": "气球的缩小是有意的。", "feat": "n." },
    { "word": "flu", "zh": "流感、感冒", "soundmark": "/fluː/", "eg": "I caught the flu and had to stay in bed.", "egzh": "我得了流感，不得不卧床休息。", "feat": "n." },
    { "word": "fluid", "zh": "液体、流体", "soundmark": "/ˈfluːɪd/", "eg": "Water is a common example of a fluid.", "egzh": "水是流体的一个常见例子。", "feat": "n." },
    { "word": "fluent", "zh": "流利的、流畅的", "soundmark": "/ˈfluːənt/", "eg": "He is fluent in three languages.", "egzh": "他能流利地说三种语言。", "feat": "adj." },
    { "word": "influence", "zh": "影响、影响力", "soundmark": "/ˈɪnflʊəns/", "eg": "Her words can have a great influence on people.", "egzh": "她的话语对人们有很大的影响力。", "feat": "n." },
    { "word": "influential", "zh": "有影响力的、有影响的", "soundmark": "/ˌɪnfluˈɛnʃəl/", "eg": "He is an influential figure in the industry.", "egzh": "他是该行业的有影响力的人物。", "feat": "adj." },
    { "word": "affluent", "zh": "富裕的、富有的", "soundmark": "/ˈæfluənt/", "eg": "The neighborhood is known for its affluent residents.", "egzh": "这个社区以富有的居民而闻名。", "feat": "adj." },
    { "word": "affluence", "zh": "富裕、富裕的生活", "soundmark": "/ˈæfluəns/", "eg": "The affluence of the family is evident in their large house and luxury cars.", "egzh": "这个家庭的富裕在他们的大房子和豪车中显而易见。", "feat": "n." },
    { "word": "superfluous", "zh": "多余的、不必要的", "soundmark": "/suːˈpɜːrfluəs/", "eg": "The extra details are superfluous and can be omitted.", "egzh": "多余的细节可以省略。", "feat": "adj." },
    { "word": "fluctuate", "zh": "波动、变动", "soundmark": "/ˈflʌktʃueɪt/", "eg": "The stock prices often fluctuate with market conditions.", "egzh": "股票价格常常随市场情况波动。", "feat": "v." },
    { "word": "fluctuation", "zh": "波动、变动", "soundmark": "/ˌflʌktʃuˈeɪʃən/", "eg": "There has been a significant fluctuation in the temperature.", "egzh": "温度发生了显著的波动。", "feat": "n." },
    { "word": "forecast", "zh": "预测、预报", "soundmark": "/ˈfɔːkæst/", "eg": "The weather forecast predicts rain tomorrow.", "egzh": "天气预报预测明天会下雨。", "feat": "n./v." },
    { "word": "forehead", "zh": "额头、前额", "soundmark": "/ˈfɔːrhɛd/", "eg": "She touched her forehead to check her temperature.", "egzh": "她摸了摸额头以检查体温。", "feat": "n." },
    { "word": "foresee", "zh": "预见、预知", "soundmark": "/fɔːˈsiː/", "eg": "He could foresee the potential problems.", "egzh": "他能预见潜在的问题。", "feat": "v." },
    { "word": "beforehand", "zh": "事先、预先", "soundmark": "/bɪˈfɔːrhænd/", "eg": "Make sure to plan everything beforehand.", "egzh": "确保提前计划好一切。", "feat": "adv." },
    { "word": "form", "zh": "形式、表格", "soundmark": "/fɔːrm/", "eg": "Please fill out this form with your information.", "egzh": "请填写这张表格，提供您的信息。", "feat": "n." },
    { "word": "formation", "zh": "形成、形态", "soundmark": "/fɔːrˈmeɪʃən/", "eg": "The formation of the new government was a historic event.", "egzh": "新政府的形成是一件历史性事件。", "feat": "n." },
    { "word": "formula", "zh": "公式、配方", "soundmark": "/ˈfɔːrmjʊlə/", "eg": "He used a special formula to calculate the result.", "egzh": "他使用了一个特殊的公式来计算结果。", "feat": "n." },
    { "word": "formulate", "zh": "制定、阐明", "soundmark": "/ˈfɔːrmjʊleɪt/", "eg": "They need to formulate a plan for the project.", "egzh": "他们需要制定一个项目计划。", "feat": "v." },
    { "word": "uniform", "zh": "制服、统一的", "soundmark": "/ˈjuːnɪfɔːm/", "eg": "The school requires students to wear a uniform.", "egzh": "学校要求学生穿制服。", "feat": "n./adj." },
    { "word": "inform", "zh": "通知、告知", "soundmark": "/ɪnˈfɔːrm/", "eg": "I will inform the team about the changes.", "egzh": "我会通知团队有关变更的情况。", "feat": "v." },
    { "word": "information", "zh": "信息、资讯", "soundmark": "/ˌɪnfəˈmeɪʃən/", "eg": "The website provides valuable information.", "egzh": "这个网站提供有价值的信息。", "feat": "n." },
    { "word": "reform", "zh": "改革、改善", "soundmark": "/rɪˈfɔːrm/", "eg": "The government plans to reform the healthcare system.", "egzh": "政府计划改革医疗体系。", "feat": "v./n." },
    { "word": "conform", "zh": "遵守、符合", "soundmark": "/kənˈfɔːrm/", "eg": "You should conform to the company's rules and regulations.", "egzh": "你应该遵守公司的规章制度。", "feat": "v." },
    { "word": "transform", "zh": "转变、改变", "soundmark": "/trænsˈfɔːrm/", "eg": "The renovation will transform the old building into a modern space.", "egzh": "翻新将把这座老建筑转变成一个现代空间。", "feat": "v." },
    { "word": "perform", "zh": "表演、执行", "soundmark": "/pərˈfɔːrm/", "eg": "The actors will perform on stage tonight.", "egzh": "演员们今晚将在舞台上表演。", "feat": "v." },
    { "word": "performance", "zh": "表现、性能", "soundmark": "/pərˈfɔːrməns/", "eg": "The car's performance on the track was impressive.", "egzh": "这辆车在赛道上的表现令人印象深刻。", "feat": "n." },
    { "word": "effort", "zh": "努力、尽力", "soundmark": "/ˈɛfət/", "eg": "With great effort, they completed the project on time.", "egzh": "在极大的努力下，他们按时完成了项目。", "feat": "n." },
    { "word": "comfort", "zh": "舒适、安慰", "soundmark": "/ˈkʌmfərt/", "eg": "The soft cushions provide comfort to the guests.", "egzh": "软垫为客人提供了舒适。", "feat": "n." },
    { "word": "comfortable", "zh": "舒适的、舒服的", "soundmark": "/ˈkʌmfərtəbl/", "eg": "The room was cozy and comfortable.", "egzh": "房间温馨舒适。", "feat": "adj." },
    { "word": "force", "zh": "力量、强制", "soundmark": "/fɔːrs/", "eg": "They used force to open the locked door.", "egzh": "他们使用力量打开锁住的门。", "feat": "n./v." },
    { "word": "enforce", "zh": "强制执行、实施", "soundmark": "/ɪnˈfɔːrs/", "eg": "The police are here to enforce the law.", "egzh": "警察在这里执行法律。", "feat": "v." },
    { "word": "enforcement", "zh": "强制、执行", "soundmark": "/ɪnˈfɔːrsmənt/", "eg": "The enforcement of the new regulations will begin next month.", "egzh": "新规定的执行将于下个月开始。", "feat": "n." },
    { "word": "reinforce", "zh": "加强、增强", "soundmark": "/ˌriːɪnˈfɔːrs/", "eg": "The additional support will reinforce the structure.", "egzh": "额外的支持将加强这个结构。", "feat": "v." }, 
]
